const TITLE = 'Zero OS';
const DESCRIPTION =
  'Zero OS is an open-source productivity platform with AI-powered modules for email, calendar, tasks, agents, notifications, and more. Self-hosted and privacy-first.';

export const siteConfig = {
  title: TITLE,
  description: DESCRIPTION,
  icons: {
    icon: '/favicon.ico',
  },
  applicationName: 'Zero OS',
  creator: '@nizzyabi @bruvimtired @ripgrim @needleXO @dakdevs @mrgsub',
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    images: [
      {
        url: `${import.meta.env.VITE_PUBLIC_APP_URL}/og.png`,
        width: 1200,
        height: 630,
        alt: TITLE,
      },
    ],
  },
  category: 'Email Client & Productivity Platform',
  alternates: {
    canonical: import.meta.env.VITE_PUBLIC_APP_URL,
  },
  keywords: [
    'Zero OS',
    'Productivity Platform',
    'Open Source',
    'Email Client',
    'Gmail Alternative',
    'Webmail',
    'Secure Email',
    'Email Management',
    'Email Platform',
    'Self-Hosted',
    'AI-Powered',
    'Email',
    'Calendar',
    'Tasks',
    'Agents',
    'Notifications',
    'Scheduling',
    'Workspaces',
    'Privacy-First',
    'Communication Tool',
    'Business Productivity',
    'Personal Productivity',
    'Productivity',
    'Business Email',
    'Personal Email',
    'Mail Server',
    'Email Software',
    'Collaboration',
    'Digital Workspace',
    'Web Application',
    'API Integration',
    'Message Management',
    'Digital Communication',
    'Email Service',
  ],
  //   metadataBase: new URL(import.meta.env.VITE_PUBLIC_APP_URL!),
};
