import { cloudflare } from '@cloudflare/vite-plugin';
import { paraglideVitePlugin } from '@inlang/paraglide-js';
import { reactRouter } from '@react-router/dev/vite';
import tailwindcss from "@tailwindcss/vite";
import dedent from 'dedent';
import { resolve } from 'path';
import { defineConfig } from 'vite';
import babel from 'vite-plugin-babel';
import oxlintPlugin from 'vite-plugin-oxlint';
import tsconfigPaths from 'vite-tsconfig-paths';

const ReactCompilerConfig = {
  /* ... */
};

// Build plugin list allowing any factory to return a single plugin or an array.
function norm(entry: any): any[] {
  if (!entry) return [];
  return Array.isArray(entry) ? entry : [entry];
}

const rawPlugins = [
  tsconfigPaths(),
  process.env.OXLINT === '1' ? oxlintPlugin() : null,
  reactRouter(),
  cloudflare(),
  babel({
    filter: /\.[jt]sx?$/,
    babelConfig: {
      presets: ['@babel/preset-typescript'],
      plugins: [['babel-plugin-react-compiler', ReactCompilerConfig]],
    },
  }),
  tailwindcss(),
  {
    name: 'add-headers',
    applyToEnvironment: (env: any) => env.name === 'client',
    generateBundle() {
      this.emitFile({
        fileName: '_headers',
        type: 'asset',
        source: dedent`
          # Autogenerated

          /assets/*
            ! Cache-Control
              Cache-Control: public, immutable, max-age=31536000
        `,
      });
    },
  },
  paraglideVitePlugin({
    project: './project.inlang',
    outdir: './paraglide',
    strategy: ['cookie', 'baseLocale'],
  }),
];

const pluginList = rawPlugins.flatMap(norm);
// Diagnostics (temporary) to verify plugin names, especially react-router
// eslint-disable-next-line no-console
console.log('[vite-config][diagnostic] Plugin names:', pluginList.map(p => p && p.name));

export default defineConfig({
  plugins: pluginList,
  server: {
    port: 3500,
    host: true, // listen on all interfaces when run inside container
    strictPort: true, // fail fast instead of picking a random free port
    // Proxy API calls to the backend dev server to keep same-origin cookies in dev
    // This helps avoid CORS and auth cookie issues when the frontend is on 3500 and backend on 8787
    proxy: {
      '/api': {
        target: 'http://localhost:8787',
        changeOrigin: true,
        secure: false,
      },
      '/monitoring': {
        target: 'http://localhost:8787',
        changeOrigin: true,
        secure: false,
      },
    },
    warmup: {
      clientFiles: ['./app/**/*', './components/**/*'],
    },
  },
  //   ssr: {
  //     optimizeDeps: {
  //       include: ['novel', '@tiptap/extension-placeholder'],
  //     },
  //   },
  esbuild: {
    pure: ['console.log'],
  },
  build: {
    sourcemap: false,
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, '.'),
      tslib: 'tslib/tslib.es6.js',
    },
  },
});
