<#
Generate a dated summary of modified/deleted files between upstream/staging and local staging and save it to:
 - .upstream-diffs/changed-files-YYYY-MM-DD.md (summary list of M/D files)

Usage:
    .\.upstream-diffs\generate-upstream-diff.ps1

This script must be run from repo root. It will fetch upstream, compute the diff,
and write files into `.upstream-diffs/`.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Ensure-RepoRoot {
    $repoRoot = Resolve-Path -Path '.'
    return $repoRoot.Path
}

function Ensure-Dir($path) {
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path | Out-Null
    }
}

try {
    $root = Ensure-RepoRoot
    Push-Location $root

    Write-Host "Fetching upstream..."
    git fetch upstream --prune --tags

    $date = Get-Date -Format yyyy-MM-dd
    $summaryFile = Join-Path -Path "$root" -ChildPath ".upstream-diffs/changed-files-$date.md"

    Ensure-Dir (Join-Path $root '.upstream-diffs')

    Write-Host "Parsing modified and deleted files to create summary -> $summaryFile"
    $nameStatus = git diff --name-status upstream/staging...staging
    $lines = $nameStatus -split "`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }

    $modified = @()
    $deleted = @()

    foreach ($line in $lines) {
        if ($line -match '^[M]\s+(.*)') { $modified += $Matches[1].Trim() }
        elseif ($line -match '^[D]\s+(.*)') { $deleted += $Matches[1].Trim() }
    }

    $sb = New-Object System.Text.StringBuilder
    $sb.AppendLine("## Upstream vs Local staging changes - $date") | Out-Null
    $sb.AppendLine() | Out-Null
    $sb.AppendLine('Generated by: `git diff --name-status upstream/staging...staging` on ' + $date) | Out-Null
    $sb.AppendLine() | Out-Null
    $sb.AppendLine("Summary") | Out-Null
    $sb.AppendLine("-------") | Out-Null
    $sb.AppendLine() | Out-Null
    if ($modified.Count -gt 0) {
        $sb.AppendLine("Modified (M)") | Out-Null
        foreach ($f in $modified) { $sb.AppendLine("- $f") | Out-Null }
        $sb.AppendLine() | Out-Null
    } else {
        $sb.AppendLine("No modified files found.") | Out-Null
        $sb.AppendLine() | Out-Null
    }

    if ($deleted.Count -gt 0) {
        $sb.AppendLine("Deleted (D)") | Out-Null
        foreach ($f in $deleted) { $sb.AppendLine("- $f") | Out-Null }
        $sb.AppendLine() | Out-Null
    } else {
        $sb.AppendLine("No deleted files found.") | Out-Null
        $sb.AppendLine() | Out-Null
    }

    $sb.AppendLine("Notes") | Out-Null
    $sb.AppendLine("-----") | Out-Null
    $sb.AppendLine("This summary was generated on $date. Use git directly to produce a full patch if needed.") | Out-Null
    $sb.AppendLine() | Out-Null
    $sb.AppendLine('How to regenerate: run `.upstream-diffs/generate-upstream-diff.ps1` from repository root in PowerShell.') | Out-Null

    $sb.ToString() | Out-File -FilePath $summaryFile -Encoding UTF8

    Write-Host "Created: $summaryFile"

} catch {
    Write-Error "Failed: $_"
} finally {
    Pop-Location
}
